CREATE TABLE IF NOT EXISTS `sensors` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `last_temparature` NUMERIC(15,2) NOT NULL,
    `updateat` DATETIME NOT NULL,
    `enabled` SMALLINT
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;