CREATE TABLE IF NOT EXISTS `alerts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `max_temperature` NUMERIC(15,2) NOT NULL,
    `min_temperature` NUMERIC(15,2) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;